// Utility functions for display formatting

/**
 * Check if an email is auto-generated from phone login
 * These emails should be hidden from display
 */
export const isAutoGeneratedEmail = (email: string | null | undefined): boolean => {
  if (!email) return true;
  // Check for any phone-based auto-generated email patterns
  return email.includes('@phone.') || email.includes('@phone');
};

/**
 * Get display-friendly email (returns null if auto-generated)
 */
export const getDisplayEmail = (email: string | null | undefined): string | null => {
  if (!email || isAutoGeneratedEmail(email)) return null;
  return email;
};

/**
 * Get display-friendly phone (returns null if it's actually an auto-generated email pattern)
 */
export const getDisplayPhone = (phone: string | null | undefined): string | null => {
  if (!phone) return null;
  // If phone contains email patterns, it's not a real phone number
  if (phone.includes('@phone.') || phone.includes('@phone') || phone.includes('@')) return null;
  return phone;
};

/**
 * Get the best available contact info to display (phone preferred, then real email)
 */
export const getDisplayContact = (phone: string | null | undefined, email: string | null | undefined): string | null => {
  const displayPhone = getDisplayPhone(phone);
  if (displayPhone) return displayPhone;
  
  const displayEmail = getDisplayEmail(email);
  return displayEmail;
};
